<a href="https://colab.research.google.com/github/michaelherediaperez/mecanica_de_solidos_un/blob/main/codigos/cap_02/02_08_01_ejemplo_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo sección 2.8.1

|Quién | Fecha | Qué hizo |
| ---  | ---   | ---      |
|Michael Heredia Pérez, <mherediap@unal.edu.co> | Julio 14, 2022 | Conversión de código de MAXIMA a Python|

Considere un puto de un sólido bidimensional en el cual los esfuerzos son $\sigma_x=$ 3 Pa, $\sigma_y=$ 2 Pa y $\tau_{xy}=$ -4 Pa. Se pide:

* Plantear la matriz de tensiones $\underline{\underline{\sigma}}$ correspondiente.
* Calcular el polinomio característico asociado a $\underline{\underline{\sigma}}$.
* Calcular la dirección y magnitud de los esfuerzos principales.

In [1]:
import numpy as np  # Librería para cálculo algebráico

In [2]:
# Para mejorcomprensión, defino los componentes de la matriz sigma__.
sx  = 3 
sy  = 2
txy = -4

# Defino la matriz sigma__
sigma__ = np.array([[sx,  txy],
                    [txy, sy]])

$\underline{\underline{\sigma}}=$

In [3]:
sigma__

array([[ 3, -4],
       [-4,  2]])

En el ```main.pdf``` se menciona una solución con el comando ```poly``` de Matlab para obtener los coeficientes del polinomio característico. En Python, su equivalente es ```numpy.poly()```.

In [4]:
np.poly(sigma__)

array([  1.,  -5., -10.])

En el ```main.pdf``` se menciona una solución con el comando ```eigenvalues``` de MAXIMA para calcular la magnitud de los esfuerzos principales. En Python, su equivalente es ```numpy.linalg.eigvals()``` el cual calcula los valores propios de una matriz.


In [5]:
np.linalg.eigvals(sigma__)

array([ 6.53112887, -1.53112887])

Para el cálculo de las direcciones, se requeren los vectores propios de la matriz $\underline{\underline{\sigma}}$, se podría hacer con el comando ```np.linalg.eig()``` que calcula tanto los valores como los vectores propios. Es similar al comando ```eig``` de MAXIMA.

In [6]:
valp, vecp = np.linalg.eig(sigma__)

Los valores propios representan la magnitud de los esfuerzos principales,

$[(\sigma_1)_{xy}, [(\sigma_2)_{xy}] = $  

In [7]:
valp

array([ 6.53112887, -1.53112887])

Los vectores propios representan la dirección de los esfuerzos principales.

In [8]:
vecp

array([[ 0.74967818,  0.66180256],
       [-0.66180256,  0.74967818]])

$\hat{n_1}^\intercal = $

In [9]:
vecp[0]

array([0.74967818, 0.66180256])

$\hat{n_2}^\intercal = $

In [10]:
vecp[1]

array([-0.66180256,  0.74967818])