<a href="https://colab.research.google.com/github/michaelherediaperez/mecanica_de_solidos_un/blob/main/codigos/cap_02/02_08_02_ejemplos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo (verificación) sección 2.8.2.

|Quién | Fecha | Qué hizo |
| ---  | ---   | ---      |
|Michael Heredia Pérez, <mherediap@unal.edu.co> | Julio 14, 2022 | Conversión de código de MAXIMA a Python|
|Diego Andrés Alvarez, <daalvarez@unal.edu.co>  | Septiembre 13, 2022 | Mejorando los comentarios |

Considere un punto P sometido a los esfuerzos $\sigma_x=$ 1 Pa, $\sigma_y=$ 3 Pa, $\sigma_z= \tau_{xy} = \tau_{xz} =$ 0 Pa y $\tau_{yz}=$ 2 Pa. Encuentre las direcciones, las magnitudes y los planos osbre los que actúan los esfuerzos principales  


In [1]:
import numpy as np  # Librería para cálculo algebráico.

## Verificación del sistema de coordenadas de la mano derecha

En MAXIMA se trabaja con la librería ```vect``` que define el producto cruz como la combinación del operador ```~``` y la función ```express()```; sin embargo en numpy basta con emplear la función ```numpy.cross```.

In [2]:
# Defino los vectores.
n1  = np.array([ 0, 2/np.sqrt(5), 1/np.sqrt(5) ])
n2a = np.array([ 1,            0,            0 ])   # n2 del ejercicio.
n2b = np.array([-1,            0,            0 ])   # n2 con sentido contrario.

In [3]:
# Se calcula el producto cruz: n1 x n2a.
n3a = np.cross(n1, n2a)
n3a

array([ 0.        ,  0.4472136 , -0.89442719])

In [4]:
# Se calcula el producto cruz: n1 x n2b
n3b = np.cross(n1, n2b)
n3b

array([ 0.        , -0.4472136 ,  0.89442719])

Verifique estos resultados según las conclusiones del ejercicio.

## Verificación de la no existencia de esfuerzos cortantes

Se construye la matriz de esfuerzos $\underline{\underline{\boldsymbol{\sigma}}}$ y de transformación $\boldsymbol{T}$:

In [5]:
sigma = np.array([[ 1, 0, 0 ],
                  [ 0, 3, 2 ],
                  [ 0, 2, 0 ]])

# Recuerde, T = [n1, n2, n3]
T = np.array([[            0, 1,             0 ],
              [ 2/np.sqrt(5), 0,  1/np.sqrt(5) ],
              [ 1/np.sqrt(5), 0, -2/np.sqrt(5) ]])

La matriz de esfeurzos en el nuevo sistema de coordenadas, $\underline{\underline{\boldsymbol{\sigma}}}'$

In [6]:
sigmaP = T.T@sigma@T
sigmaP.round(5)

array([[ 4.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0., -1.]])