<a href="https://colab.research.google.com/github/michaelherediaperez/mecanica_de_solidos_un/blob/main/codigos/cap_03/03_04_03_ejemplo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo sección 3.4.3. más de tres galgas extensométricas

|Quién | Fecha | Qué hizo |
| ---  | ---   | ---      |
|Michael Heredia Pérez, <mherediap@unal.edu.co> | Julio 16, 2022 | Conversión de código de MATLAB a Python|
|Michael Heredia Pérez, <mherediap@unal.edu.co> | Marzo 30, 2023 | Mejorando la explicación del procedimiento|

In [1]:
import numpy as np                  # Librería para cálculo algebráico.

Asignamos la información del problema: los ángulos a los cuales se ubican las 5 galgas, y las mediciones que tomaron.

In [2]:
# Medición              Ángulo [°]
eA =  3.0012e-4;        tA = 0
eB =  3.4521e-4;        tB = 72
eC =  1.4935e-3;        tC = 144
eD = -4.0924e-4;        tD = 216
eE =  1.5207e-3;        tE = 288

Aplicamos la ecuación (3.24a): $$\varepsilon_{x'}(\theta) = \varepsilon_x\cos^2\theta + \varepsilon_y\sin^2\theta + \varepsilon_{xy}\sin\theta\cos\theta.$$

Queda un sistema de 5 ecuaciones con 3 incógnitas, matricialmente, esto lo podemos relacionar así:
\begin{equation*}
\begin{pmatrix}
\varepsilon_A \\
\varepsilon_B \\
\varepsilon_C \\
\varepsilon_D \\
\varepsilon_E 
\end{pmatrix} = \boldsymbol{A}_{5 \times 3} \begin{pmatrix} \varepsilon_x \\ \varepsilon_y \\ \varepsilon_{xy} \end{pmatrix}
\end{equation*}

Es un sistema de la forma $\boldsymbol{b} = \boldsymbol{Ax}$, donde $\boldsymbol{A}$ no es invertible ya que no es cuadrada. Se puede resolver usando la *pseudoinversa de Moore-Penrose* (ver, por ejemplo, \href{https://en.wikipedia.org/wiki/Moore-Penrose_inverse}{https://en.wikipedia.org/wiki/Moore-Penrose_inverse}):

$$\boldsymbol{A}^{*} = (\boldsymbol{A}^T\boldsymbol{A})^{-1}\boldsymbol{A}$$

La matriz $\boldsymbol{A}$ es una matriz de senos y cosenos, y tenemos ángulos medidos en grados. Python no cuenta con una función ```cosd()``` o ```sind()```, las cuales calculan cosenos y senos, respectivamente, con el argumento en grados (*degrees*), podríamos usar la función ```np.deg2rad()``` para convertir de grados a radianes y hacer el cálculo, o construir las funciones simplemente para no interrumpir la lectura de la próxima matriz:

In [3]:
cosd = lambda t : np.cos(np.deg2rad(t)) # Calcula el coseo de ángulos en grados.
sind = lambda t : np.sin(np.deg2rad(t)) # Calcula el seno de ángulos en grados.

Creamos la matriz $\boldsymbol{A}$ y definimos el vector \boldsymbol{b}

In [4]:
A = np.array([[ cosd(tA)**2, sind(tA)**2, sind(2*tA) ],
              [ cosd(tB)**2, sind(tB)**2, sind(2*tB) ],
              [ cosd(tC)**2, sind(tC)**2, sind(2*tC) ],
              [ cosd(tD)**2, sind(tD)**2, sind(2*tD) ],
              [ cosd(tE)**2, sind(tE)**2, sind(2*tE) ]])

b = np.array([eA, eB, eC, eD, eE])

In [5]:
A

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.0954915 ,  0.9045085 ,  0.58778525],
       [ 0.6545085 ,  0.3454915 , -0.95105652],
       [ 0.6545085 ,  0.3454915 ,  0.95105652],
       [ 0.0954915 ,  0.9045085 , -0.58778525]])

Calculamos la ecuación (3.27) $$\boldsymbol{A}^{*} = (\boldsymbol{A}^T\boldsymbol{A})^{-1}\boldsymbol{A}$$. En Python, otra forma de calcular la inversa de una matriz algebráicamente es con el comando ```.T```, en ejemplos anteriores no se ha utilizado para no confundirse con la matriz de transformación $T$. 

In [6]:
A_seudo = np.linalg.inv(A.T@A) @ A.T 
x1 =  A_seudo @ b
x1

array([ 0.00030031,  0.00099981, -0.00100022])

Lo anterior es equivalente la función ```numpy.linalg.pinv()```

In [7]:
x2 = np.linalg.pinv(A) @ b
x2

array([ 0.00030031,  0.00099981, -0.00100022])

In [8]:
(x1 - x2).round(8)

array([0., 0., 0.])

En Python, no es posible realizar la operación con ```/``` si las dimensiones no son congruentes, como podemos ver aquí:

In [9]:
x3 = A/b
x3

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

En Python el comando ```\``` está reservado para hacer secuencias de escape, lo que nos daría el siguiente error:

In [10]:
x4 = A\b
x4

SyntaxError: unexpected character after line continuation character (2131881339.py, line 1)