<a href="https://colab.research.google.com/github/michaelherediaperez/mecanica_de_solidos_un/blob/main/codigos/cap_03/03_04_02_ejemplo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo sección 3.4.2. Cambio de base

|Quién | Fecha | Qué hizo |
| ---  | ---   | ---      |
|Michael Heredia Pérez, <mherediap@unal.edu.co> | Julio 16, 2022 | Conversión de código de MAXIMA a Python|
|Michael Heredia Pérez, <mherediap@unal.edu.co> | Marzo 30, 2022 | Explicando mejor el procedimiento |

In [1]:
import numpy as np                  # Librería para cálculo algebráico.

Se define la función vector unitario. El simil de la definción de una función en MAXIMA ```@```, son las funciones ```lambda``` de Python.

In [2]:
vector_unitario = lambda x : x/np.linalg.norm(x)

Se calculan las direcciones para los vectores $\hat{\boldsymbol{e}}_{1'}$, $\hat{\boldsymbol{e}}_{2'}$ y $\hat{\boldsymbol{e}}_{3'}$

In [8]:
# Identificamos 3 puntos.
p_dir_x             = np.array([1, -2,  -3])
dir_normal_plano    = np.array([2, 1,  5])
origen_coord_xpypzp = np.array([4, 2, -5])

# La dirección de e1gp respecto al nuevo sistema de coordenadas se calcula como 
# la distancia normalizada entre (2, 1, 5) y (4, 2, -5), a.k.a. el nuevo oriden 
# de coordenadas. 
e1gp = vector_unitario(p_dir_x - origen_coord_xpypzp)

# e3gp está dado respecto a la base xyz, además sale del origen de coordenadas 
# x'y'z' dado por le punto (4,2,-5), de hecho forman un plano, así que 
# simplemente se normaliza.
e3gp = vector_unitario(dir_normal_plano)

# e2gp debe formar junto con e1gp y e3gp un sistema de la mano derecha, por lo 
# tanto se obtiene como e2gp = e3gp X e1gp
e2gp = np.cross(e3gp, e1gp)          

In [10]:
# Verifiquemos qué es este cálculo:
p_dir_x - origen_coord_xpypzp

array([-3, -4,  2])

Se define la matriz de transformación $T = [\hat{\boldsymbol{e}}_{1'}, \hat{\boldsymbol{e}}_{2'}, \hat{\boldsymbol{e}}_{3'}]$

In [11]:
# Recordemos que se forma con los vectores columna, numpy los trabaja como 
# vectores fila, así que debo trasnponer la matriz.
T = np.array([e1gp, e2gp, e3gp]).transpose()    # .T
T

array([[-0.55708601,  0.74586985,  0.36514837],
       [-0.74278135, -0.64416033,  0.18257419],
       [ 0.37139068, -0.16951588,  0.91287093]])

Sabiendo que la lectura de las galgas es: 
\begin{align*}
\varepsilon_A &= 10^{-3}, \\
\varepsilon_B &= 2.1\times10^{-3},\\
\varepsilon_C &= -1.7\times10^{-3},\\
\end{align*}
se determinan las deformacion es $\varepsilon_{x'}$, $\varepsilon_{y'}$ y $\varepsilon_{x'y'}$ utilizando las ecuaciones (3.26) del ejemplo anterior.

In [12]:
# Lectura de las galgas
eA =    1e-3  
eC = -1.7e-3  
eB =  2.1e-3  

# Aplicación de las ecuaciones (3.26)
e_xp   = eA
e_yp   = eC 
e_xpyp = eB - (eA + eC)/2

Se define la matriz de deformaciones $\underline{\underline{\boldsymbol{\varepsilon}}}'$ en $x'$, $y'$, $z'$. Aquí estamos teniendo en cuenta el estado de deformación plana $\varepsilon_{z'} = \varepsilon_{x'z'} 0 \varepsilon_{y'z'} = 0$   

In [13]:
epsilonP = np.array([[e_xp,   e_xpyp, 0],
                     [e_xpyp,   e_yp, 0],
                     [0,           0, 0]])

Calculamos la matriz de deformaciones $\underline{\underline{\boldsymbol{\varepsilon}}}$ en el sistema de coordenadas globales $x$, $y$, $z$ mediante la ecuación $$\underline{\underline{\boldsymbol{\varepsilon}}} = \boldsymbol{T}\underline{\underline{\boldsymbol{\varepsilon}}}'\boldsymbol{T}^T$$

In [14]:
epsilon = T @ epsilonP @ T.transpose()
epsilon

array([[-0.00267142,  0.00075242,  0.00091808],
       [ 0.00075242,  0.00219083, -0.00073913],
       [ 0.00091808, -0.00073913, -0.00021941]])

Extraemos todas las deformaciones:

In [21]:
# Para ex:
print(f"e_x  = {epsilon[0][0].round(6)}")
print(f"e_y  = {epsilon[1][1].round(6)}")
print(f"e_z  = {epsilon[2][2].round(6)}") 
print(f"e_xy = {epsilon[0][1].round(6)}") 
print(f"e_xz = {epsilon[0][2].round(6)}") 
print(f"e_yz = {epsilon[1][2].round(6)}") 


e_x  = -0.002671
e_y  = 0.002191
e_z  = -0.000219
e_xy = 0.000752
e_xz = 0.000918
e_yz = -0.000739


Observe que en el sistema de coordenadas gloables si existe la deformación longitudinal $\varepsilon_z$ y sus pares angulares en el plano $\varepsilon_{xz}$ y $\varepsilon_{yz}$. 